### ISSUE TITLE
Cannot install after building because the libraries are not installed

### ISSUE THREAD

**Issue by antonio-couto** [juha-h/bcg729-deb#1]
Thanks for the tool, but i am trying to install on Ubuntu 20.04 and after building the pkg I am trying to intall using the command:

sudo dpkg -i libbcg729-*.deb

The problem is that the libraries are not installed, i check the /usr/lib directory and there are no bcg729 libraries.

Any tip to solve this problem ?

Thanks agains.

**Comment by juha-h** [comment]
Antonio Couto writes:

> Thanks for the tool, but i am trying to install on Ubuntu 20.04 and
> after building the pkg I am trying to intall using the command: 
> 
> sudo dpkg -i libbcg729-*.deb
> 
> The problem is that the libraries are not installed, i check the
> /usr/lib directory and there are no bcg729 libraries. 
> 
> Any tip to solve this problem ?

Check the contents of the package with `dpkg --contents <package>` and
you will see where lib is installed, for example:
```
$ dpkg --contents libbcg729_1.1.0-0_amd64.deb 
drwxr-xr-x root/root         0 2020-11-20 09:12 ./
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/lib/
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/lib/x86_64-linux-gnu/
-rw-r--r-- root/root     64040 2020-11-20 09:12 ./usr/lib/x86_64-linux-gnu/libbcg729.so.0
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/share/
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-11-20 09:12 ./usr/share/doc/libbcg729/
-rw-r--r-- root/root       144 2020-11-20 09:12 ./usr/share/doc/libbcg729/changelog.Debian.gz
-rw-r--r-- root/root       344 2020-11-20 09:12 ./usr/share/doc/libbcg729/changelog.gz
-rw-r--r-- root/root      3459 2020-11-20 09:12 ./usr/share/doc/libbcg729/copyright
```

**Comment by antonio-couto** [comment]
I run the command to install on each pkg and works, i check and it´s ok.
Thanks a lot, take care.

udo dpkg -l | grep libbcg729
ii  libbcg729:amd64                            1.1.0-0                             amd64        ITU G.729 Annex A compatible audio codec
ii  libbcg729-dbg:amd64                        1.1.0-0                             amd64        Debug symbols for the ITU G.729 compatible audio codec
ii  libbcg729-dbgsym:amd64                     1.1.0-0                             amd64        debug symbols for libbcg729
ii  libbcg729-dev:amd64                        1.1.0-0                             amd64        Development files for the ITU G.729 compatible audio codec
